### ISSUE TITLE
Same quote when requested from AFNetworking GET request

### ISSUE THREAD

**Issue by BHughes3388** [jamesseanwright/ron-swanson-quotes#1]
Like the title says, I wrote a very simple ios app to return a random quote. Every time it runs it returns the same quote, which ironically enough is also the one you have in the ReadMe. (capitalism: God's way of....)

Could just be I'm doing something wrong tho?

**Comment by jamesseanwright** [comment]
I'm successfully getting different quotes each time I request the `/quotes` endpoint via HTTP GET. Which language/technologies are you using? Is it possible that your framework of choice implements a caching layer?

Let me know, and I will investigate further :)

**Comment by jamesseanwright** [comment]
Also, I've checked the response in further detail and I can't see any `Cache-Control` or similar headers, although I did notice an `ETag` header, which may have some bearing on cached responses.

**Comment by BHughes3388** [comment]
It was being cached, I added some code to ignore caching and it's working
as it should now. Thanks for the help!

**Comment by jamesseanwright** [comment]
Excellent, glad you got it working :)
