### ISSUE TITLE
Swagger/Open API json

### ISSUE THREAD

**Issue by chrisgali01** [jamesseanwright/ron-swanson-quotes#7]
I could use a swagger(open api) json structure for this cool API

**Comment by jamesseanwright** [comment]
Hey @chrisgali01,

I'm happy to take a look at this when I have time. I'll keep you posted!

**Comment by chrisgali01** [comment]
Thank you James.

**Comment by chrisgali01** [comment]
James  I created a Swagger 2.0 specification for you.

https://app.swaggerhub.com/apis/chrisgali/RonSwansonQuote/1.0.0

Enjoy!

**Comment by jamesseanwright** [comment]
Foremost, sorry for the lack of response! I've been super-busy with client work and other projects.

Your schema looks great. Thanks so much for your time and efforts! ☺️ I'll get this added to the repo and served from an endpoint in the Node.js app.

Cheers,
James

**Comment by chrisgali01** [comment]
No problem.  Here's the OpenAPI 2.0 JSON that you'll need to expose from your site.
Something like: http://ron-swanson-quotes.herokuapp.com/v2/quotes-openapi.json
My apologies if I not using the right GitHub protocol to communicate this (I'm new to GitHub).

{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Ron Swanson Quotes",
    "description": "Service API",
    "termsOfService": "Terms of Service",
    "contact": {
      "name": "James Sean Wright",
      "email": "info@jamesseanwright.com",
      "url": "https://github.com/jamesseanwright/ron-swanson-quotes/commits?author=jamesseanwright"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "ron-swanson-quotes.herokuapp.com",
  "basePath": "/v2",
  "paths": {
    "/quotes": {
      "get": {
        "tags": [
          "Ron Swanson Quote"
        ],
        "summary": "Ron Swanson Quote",
        "description": "Returns a Ron Swanson Quote.",
        "operationId": "RonSwansonQuote",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successful request",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}

**Comment by jamesseanwright** [comment]
Do you have any familiarity with Node.js and Express? I'm happy to talk you through opening a pull request to add and serve the schema if you're interested?

**Comment by chrisgali01** [comment]
Being in the .NET world most of the last 15 years I have no familiarity with Node.js James.

**Comment by jamesseanwright** [comment]
No worries! I'll try to drop this in tonight and ping you when it's merged! :)

Welcome to GitHub by the way!

**Comment by chrisgali01** [comment]
Thanks looking forward to learning!

**Comment by jamesseanwright** [comment]
I think this will need an additional path to represent the option `{count}` parameter. I'll add this tomorrow morning.

**Comment by chrisgali01** [comment]
Cool.  Thanks for being patient with me. 👍

**Comment by jamesseanwright** [comment]
No worries! 😁

I'm pleased to let you know that this has been deployed to production, exposed via the [/v2/schema](https://ron-swanson-quotes.herokuapp.com/v2/schema) endpoint. I made the required changes to support the `/v2/quotes/{count}` path and to conform with OpenAPI 3. I also took the opportunity to update the syntax to ES2015+ and to tidy up the code.

I'll thus close this issue, but feel free to reopen it if you notice any issues.

Cheers,
James
